version: "3.7"

services:
  app:
    build:
      context: ./app/
      dockerfile: ../deploy/app/Dockerfile
    restart: always
    expose:
      - "5000"
    volumes:
      - ./app:/opt/app

  selenium:
    image: selenium/standalone-firefox:4.1.2-20220208
    restart: always
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2gb'

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app/web/static:/etc/nginx/date/static
    links:
      - app



